name: master

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: scripts/coverage.sh
      - uses: codecov/codecov-action@v1
  lint:
    name: Code Analysis
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: sh ./gradlew lint
